apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: brewrelay
    isDefault: false
    editable: true
    secureJsonData:
      password: brewrelay
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false